In [24]:
import pandas as pd
import numpy as np 
import os, sys
import seaborn as sns

df=pd.read_csv(r"D:\MLOPS\Churn_Prediction\Churn_prediction_kaggle_competition\Artifact\20260320193323\data_validation\validated\train.csv")
df.head()

,_id,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,69bc538d4dcc7400d60d9d57,24410,Male,0,No,No,3,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,94.80,298.45,No
1,69bc538d4dcc7400d60df915,47896,Male,0,Yes,Yes,58,Yes,Yes,Fiber optic,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,108.15,6431.05,No
2,69bc538d4dcc7400d60e0359,50524,Male,0,No,No,72,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),25.60,1463.75,No
3,69bc538d4dcc7400d60d8d43,20294,Female,0,Yes,Yes,70,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),20.00,1414.75,No
4,69bc538d4dcc7400d60e85c1,83908,Male,0,No,No,71,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,One year,No,Bank transfer (automatic),89.20,6333.80,No

In [25]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [26]:
df.drop(columns=["_id" , "id"], inplace=True)

In [8]:
df["SeniorCitizen"].value_counts()

SeniorCitizen
0    68386
1     8685
Name: count, dtype: int64

In [10]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Male,0,No,No,3,Yes,No,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,94.80,298.45,No
1,Male,0,Yes,Yes,58,Yes,Yes,Fiber optic,No,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,108.15,6431.05,No
2,Male,0,No,No,72,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),25.60,1463.75,No
3,Female,0,Yes,Yes,70,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),20.00,1414.75,No
4,Male,0,No,No,71,Yes,Yes,DSL,Yes,Yes,Yes,Yes,Yes,Yes,One year,No,Bank transfer (automatic),89.20,6333.80,No

In [27]:
ohe = OneHotEncoder(sparse_output=False)

categorical_cols = ["gender", "InternetService", "PaymentMethod", "Contract"]

encoded_features = ohe.fit_transform(df[categorical_cols])

encoded_df = pd.DataFrame(
    encoded_features,
    columns=ohe.get_feature_names_out(categorical_cols)
)
encoded_df.head()

,gender_Female,gender_Male,InternetService_DSL,InternetService_Fiber optic,InternetService_No,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_Month-to-month,Contract_One year,Contract_Two year
0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [20]:
encoded_df.head()

,gender_Female,gender_Male,InternetService_DSL,InternetService_Fiber optic,InternetService_No,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_Month-to-month,Contract_One year,Contract_Two year
0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
df.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
df.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [ ]:
df["PaymentMethod"].value_counts()

PaymentMethod
Electronic check             28470
Credit card (automatic)      16879
Mailed check                 16407
Bank transfer (automatic)    15315
Name: count, dtype: int64

In [ ]:
df["Contract"].value_counts()

Contract
Month-to-month    39876
Two year          23606
One year          13589
Name: count, dtype: int64

In [ ]:
df["Churn"].value_counts()

Churn
No     58760
Yes    18311
Name: count, dtype: int64

In [28]:
st=StandardScaler()
scaled_features=st.fit_transform(df[["tenure" , "MonthlyCharges" , "TotalCharges"]])

scaled_features = pd.DataFrame(
    scaled_features , 
    columns=["tenure" , "MonthlyCharges" , "TotalCharges"]
)

scaled_features.head()

     tenure  MonthlyCharges  TotalCharges
0 -1.273817        0.951272     -0.894276
1  0.885581        1.381487      1.709838
2  1.435246       -1.278758     -0.399449
3  1.356723       -1.459223     -0.420257
4  1.395984        0.770807      1.668542

In [29]:
df["OnlineSecurity"].replace({"No internet service" : "No"} , inplace=True)
df["OnlineBackup"].replace({"No internet service" : "No"} , inplace=True)
df["DeviceProtection"].replace({"No internet service" : "No"} , inplace=True)
df["TechSupport"].replace({"No internet service" : "No"} , inplace=True)
df["StreamingTV"].replace({"No internet service" : "No"} , inplace=True)
df["StreamingMovies"].replace({"No internet service" : "No"} , inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_21096\2827204861.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["OnlineSecurity"].replace({"No internet service" : "No"} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\2827204861.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["OnlineBackup"].replace({"No internet service" : "No"} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\2827204861.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["DeviceProtection"].replace({"No internet service" : "No"} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\2827204861.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["TechSupport"].replace({"No internet service" : "No"} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\2827204861.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["StreamingTV"].replace({"No internet service" : "No"} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\2827204861.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["StreamingMovies"].replace({"No internet service" : "No"} , inplace=True)

In [30]:
df["Partner"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
df["Dependents"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
df["PhoneService"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
df["MultipleLines"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
df["OnlineSecurity"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
df["OnlineBackup"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
df["DeviceProtection"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
df["TechSupport"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
df["StreamingTV"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
df["StreamingMovies"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
df["Churn"].replace({"Yes" : 1 , "No" : 0} , inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Partner"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Partner"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Dependents"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Dependents"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["PhoneService"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["PhoneService"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["MultipleLines"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["OnlineSecurity"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["OnlineBackup"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["DeviceProtection"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["TechSupport"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["StreamingTV"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["StreamingMovies"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Churn"].replace({"Yes" : 1 , "No" : 0} , inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\496900380.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Churn"].replace({"Yes" : 1 , "No" : 0} , inplace=True)

In [31]:
df.drop(columns=["gender" , "InternetService" ,"PaymentMethod" , "Contract"] , inplace=True)

In [21]:
df.head()

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PaperlessBilling,MonthlyCharges,TotalCharges,Churn
0,0,0,0,3,1,0,0,0,1,0,1,1,1,94.80,298.45,0
1,0,1,1,58,1,1,0,1,1,1,1,1,1,108.15,6431.05,0
2,0,0,0,72,1,1,0,0,0,0,0,0,0,25.60,1463.75,0
3,0,1,1,70,1,0,0,0,0,0,0,0,0,20.00,1414.75,0
4,0,0,0,71,1,1,1,1,1,1,1,1,0,89.20,6333.80,0

In [32]:
df["PaperlessBilling"].replace({"Yes" : 1 , "No" :0} ,inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_21096\3300936927.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["PaperlessBilling"].replace({"Yes" : 1 , "No" :0} ,inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_21096\3300936927.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["PaperlessBilling"].replace({"Yes" : 1 , "No" :0} ,inplace=True)

In [33]:
df.drop(columns=["tenure" , "MonthlyCharges" , "TotalCharges"] , inplace=True)

In [34]:
final_df = pd.concat([df , scaled_features] , axis=1)

In [35]:
final_df.head()

,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,PaperlessBilling,Churn,tenure,MonthlyCharges,TotalCharges
0,0,0,0,1,0,0,0,1,0,1,1,1,0,-1.273817,0.951272,-0.894276
1,0,1,1,1,1,0,1,1,1,1,1,1,0,0.885581,1.381487,1.709838
2,0,0,0,1,1,0,0,0,0,0,0,0,0,1.435246,-1.278758,-0.399449
3,0,1,1,1,0,0,0,0,0,0,0,0,0,1.356723,-1.459223,-0.420257
4,0,0,0,1,1,1,1,1,1,1,1,0,0,1.395984,0.770807,1.668542

In [36]:
final_df =pd.concat([df ,encoded_df ] , axis=1)
final_df.head()

,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,...,InternetService_DSL,InternetService_Fiber optic,InternetService_No,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_Month-to-month,Contract_One year,Contract_Two year
0,0,0,0,1,0,0,0,1,0,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,0,1,1,1,1,0,1,1,1,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,0,0,0,1,1,0,0,0,0,0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0,1,1,1,0,0,0,0,0,0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0,0,0,1,1,1,1,1,1,1,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [42]:
final_df.to_csv(r"D:\MLOPS\Churn_Prediction\Churn_prediction_kaggle_competition\notebook\data.csv")

In [39]:
final_df["MultipleLines"].replace({ "No phone service" : 0} , inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_21096\802034698.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_df["MultipleLines"].replace({ "No phone service" : 0} , inplace=True)

In [41]:
final_df =pd.concat([final_df ,scaled_features ] , axis=1)

In [45]:
final_df.dtypes

SeniorCitizen                                int64
Partner                                      int64
Dependents                                   int64
PhoneService                                 int64
MultipleLines                                int64
OnlineSecurity                               int64
OnlineBackup                                 int64
DeviceProtection                             int64
TechSupport                                  int64
StreamingTV                                  int64
StreamingMovies                              int64
PaperlessBilling                             int64
Churn                                        int64
gender_Female                              float64
gender_Male                                float64
InternetService_DSL                        float64
InternetService_Fiber optic                float64
InternetService_No                         float64
PaymentMethod_Bank transfer (automatic)    float64
PaymentMethod_Credit card (automatic)      float64
PaymentMethod_Electronic check             float64
PaymentMethod_Mailed check                 float64
Contract_Month-to-month                    float64
Contract_One year                          float64
Contract_Two year                          float64
tenure                                     float64
MonthlyCharges                             float64
TotalCharges                               float64
dtype: object

In [48]:
final_df.shape

(77071, 28)

In [46]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(
    sampling_strategy='auto',  # balances minority to match majority
    k_neighbors=5,             # uses 5 nearest neighbors to interpolate
    random_state=42            # reproducibility
)

X_train_res, y_train_res = sm.fit_resample(final_df.iloc[: , :-1], final_df.iloc[: , -1].astype('int64'))

In [43]:
!pip install imblearn

Collecting imblearn
  Using cached imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Collecting imbalanced-learn (from imblearn)
  Using cached imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in d:\mlops\churn_prediction\churn_prediction_kaggle_competition\churn_prediction\lib\site-packages (from imbalanced-learn->imblearn) (2.2.6)
Requirement already satisfied: scipy<2,>=1.11.4 in d:\mlops\churn_prediction\churn_prediction_kaggle_competition\churn_prediction\lib\site-packages (from imbalanced-learn->imblearn) (1.15.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in d:\mlops\churn_prediction\churn_prediction_kaggle_competition\churn_prediction\lib\site-packages (from imbalanced-learn->imblearn) (1.7.2)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn->imblearn)
  Using cached sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in d:\mlops\churn_prediction\churn_prediction_kaggle_competition\churn_prediction\lib\site-packages (from imbalanced-learn->imblearn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in d:\mlops\churn_prediction\churn_prediction_kaggle_competition\churn_prediction\lib\site-packages (from imbalanced-learn->imblearn) (3.6.0)
Using cached imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Using cached imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Using cached sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Installing collected packages: sklearn-compat, imbalanced-learn, imblearn

   ---------------------------------------- 0/3 [sklearn-compat]
   ---------------------------------------- 0/3 [sklearn-compat]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   ------------- -------------------------- 1/3 [imbalanced-learn]
   -------------------------- ------------- 2/3 [imblearn]
   ---------------------------------------- 3/3 [imblearn]

Successfully installed imbalanced-learn-0.14.1 imblearn-0.0 sklearn-compat-0.1.5

In [47]:
X_cols = final_df.drop('Churn', axis=1).columns

# Rebuild the DataFrame
X_res_df = pd.DataFrame(X_train_res, columns=X_cols)
y_res_df = pd.Series(y_train_res, name='Churn')

final_resampled_df = pd.concat([X_res_df, y_res_df], axis=1)

print(final_resampled_df.shape)

(234268, 28)

In [49]:
print("Before SMOTE:", final_df.shape)           # your full training data
print("After SMOTE: ", final_resampled_df.shape) # should be ~2x minority class

print(final_df['Churn'].value_counts())           # 58760 No / 18311 Yes
print(final_resampled_df['Churn'].value_counts()) # should be ~58760 / 58760

Before SMOTE: (77071, 28)
After SMOTE:  (234268, 28)
Churn
0    58760
1    18311
Name: count, dtype: int64
Churn
 0    58567
 1    58567
 2    58567
-1    58567
Name: count, dtype: int64

In [50]:
print(final_df.iloc[:, -1].unique())    # what values are actually in it
print(final_df.iloc[:, -1].dtype)       # what type is it

[-0.89427609  1.70983762 -0.39944947 ... -0.39486342 -0.75406177
 -0.27505279]
float64

In [51]:
final_df.head()

,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_Month-to-month,Contract_One year,Contract_Two year,tenure,MonthlyCharges,TotalCharges
0,0,0,0,1,0,0,0,1,0,1,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,-1.273817,0.951272,-0.894276
1,0,1,1,1,1,0,1,1,1,1,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.885581,1.381487,1.709838
2,0,0,0,1,1,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.435246,-1.278758,-0.399449
3,0,1,1,1,0,0,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.356723,-1.459223,-0.420257
4,0,0,0,1,1,1,1,1,1,1,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.395984,0.770807,1.668542

In [52]:
X = final_df.drop('Churn', axis=1)
y = final_df['Churn'].astype('int64')

print(y.unique())   # confirm [0, 1]
print(X.shape)      # confirm no Churn column in features

sm = SMOTE(sampling_strategy='auto', k_neighbors=5, random_state=42)
X_train_res, y_train_res = sm.fit_resample(X, y)

print(pd.Series(y_train_res).value_counts())  # should be clean 0 and 1

[0 1]
(77071, 27)
Churn
0    58760
1    58760
Name: count, dtype: int64

In [53]:
X_cols = final_df.drop('Churn', axis=1).columns

# Rebuild the DataFrame
X_res_df = pd.DataFrame(X_train_res, columns=X_cols)
y_res_df = pd.Series(y_train_res, name='Churn')

final_resampled_df = pd.concat([X_res_df, y_res_df], axis=1)

print(final_resampled_df.shape)

(117520, 28)

In [54]:
final_resampled_df.to_csv(r"D:\MLOPS\Churn_Prediction\Churn_prediction_kaggle_competition\notebook\data2.csv")